[server]
enableStaticServing = true
maxUploadSize = 200
maxMessageSize = 200
headless = true
address = "0.0.0.0"
port = 8501

[runner]
magicEnabled = false
fastReruns = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true